version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: catalog-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  catalog-service:
    build: .
    container_name: catalog-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/catalogdb
    depends_on:
      - mongo

volumes:
  mongo_data: