services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: egoist
      MINIO_ROOT_PASSWORD: egoist123
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data

  media-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: media-service
    ports:
      - "8086:8086"
    depends_on:
      - minio
    environment:
      SPRING_APPLICATION_NAME: media-service
      SERVER_PORT: 8086
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: egoist
      MINIO_SECRET_KEY: egoist123
      MINIO_BUCKET: product-images
